fix: #110 '*' char in WIT doc comments
A '*' char in the doc comments of `interface notifications` in
wit/server/notifications.wit causes `jco guest-types` to fail with

```bash
src/generated/interfaces/wasmcp-server-notifications.d.ts:41:42 - error TS1443: Module declaration names may only use ' or " quoted strings.

 41    * Send a `notifications/*/list_changed` notification to the client
                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 42    *
    ~~~~
...
 54   /**
    ~~~~~
 55    * Send a `notifications/*/updated` notification to the client
    ~~~~~~~~~~~~~

Found 1 error in src/generated/interfaces/wasmcp-server-notifications.d.ts:41

make: *** [build] Error 2
```